### ISSUE TITLE
Support multiple Branches

### ISSUE THREAD

**Issue by thombergs** [reflectoring/coderadar#1]
Currently, the annotator creates metrics for all commits, starting from HEAD and going back in time through THE FIRST parent of each commit, until there are no more parents.

Thus, branches are not supported and there is a slight randomness in the algorithm, since only the first parent is annotated.

**Comment by maximAtanasov** [comment]
We need to be able to:
 - Check-out a branch
 - Get all commits in a branch
 - Compare commits across branches

I think the following graph should do it:

![branches](https://user-images.githubusercontent.com/32562426/72720249-d2169b80-3b79-11ea-8bec-bd2450fa362c.png)

The file and module nodes will remain conntected directly to the project.
This graph is very rough and will probably change, but it should give a general idea.

Checking out a branch
 - For this we can keep using the project configuration form and add another text field where the user can enter branches. Coderadar should then checkout the branch in the local directory and modify or extend the existing graph. In the project overview the user should be able to switch between branches. For this the branch visualization from #269 can be used.
 
 - Endpoints: 
    `POST` `/project/{id}/branches` payload: 
    ```json
    {"name": "branchName"}, response: {"id": 2}
    ```

    `GET` `/project/{id}/branches` response: 
    ```json
    [{"id": 2, "name": "master"}, {"id": 3, "name": "dev"}]
    ```

    `DELETE` `/project/{id}/branches/{branchId}`

Getting commits in a branch

```
MATCH (p)-[:HAS_BRANCH]->(b:Branch)->[:CONTAINS_COMMIT]->(c) WHERE ID(p) = 1 AND b.name = "master" RETURN c
```

```
MATCH (p)-[:HAS_BRANCH]->(b:Branch)->[:CONTAINS_COMMIT]->(c) WHERE ID(p) = 1 AND b.name = "dev" RETURN c
```

I'm not yet sure if queries that depend on timestamps will work flawlessly without major changes, but I believe they should.
An additional level of indirection will be added to most queries so this might hurt performance.
The API will have to be extended in a lot of places to include a branch parameter.
