### ISSUE TITLE
replace @RequestMapping with @GetMapping, @PostMapping etc.

### ISSUE THREAD

**Issue by thombergs** [reflectoring/coderadar#110]
Spring 4.1 introduced the new annotations `@GetMapping`, `@PostMapping`, `@DeleteMapping` and `@PutMapping` which are shortcuts for `@RequestMapping(method = GET)` and so on.

Replace all occurrences of `@RequestMapping` with the matching new annotation to make the code better readable.

**Comment by KilianKrause** [comment]
This Issue will be fixed in #239.

**Comment by maximAtanasov** [comment]
Fixed in #292
