### ISSUE TITLE
IllegalStateException: could not find file ... in commit ...

### ISSUE THREAD

**Issue by pschild** [reflectoring/coderadar#114]
The problem occured during a test with the following 2 projects:
- https://github.com/square/leakcanary
- https://github.com/iluwatar/java-design-patterns

Stacktrace:
java.lang.IllegalStateException: could not find file 'decorator/src/main/java/com/iluwatar/App.java' in commit 9336284814ce7d1265025be8eb754a4738a81b8
at org.wickedsource.coderadar.job.analyze.CommitAnalyzer.findInCommit(CommitAnalyzer.java:206) ~[main/:na]
at org.wickedsource.coderadar.job.analyze.CommitAnalyzer.storeMetrics(CommitAnalyzer.java:168) ~[main/:na]
at org.wickedsource.coderadar.job.analyze.CommitAnalyzer.walkFilesInCommit(CommitAnalyzer.java:159) ~[main/:na]
at org.wickedsource.coderadar.job.analyze.CommitAnalyzer.analyzeCommit(CommitAnalyzer.java:95) ~[main/:na]
at org.wickedsource.coderadar.job.execute.JobExecutor.execute(JobExecutor.java:46) ~[main/:na]
[...]

**Comment by thombergs** [comment]
Cannot reproduce with leakcanary project. Analysis runs through completely. However, only 165 commits are analyzed and the repository contains over 300. Maybe connected.

Will try same thing with iluwatar project.

**Comment by pschild** [comment]
Hi,

I also spent some time to reproduce the exception (I analyzed the Coderadar project itself), and for me they _can_ be reproduced. Additionally I found some strange and random behaviour:  I did 7 runs and observed the **number of rows** that existed in some of the tables after the jobs had finished. **Before each run, I emptied the whole database and started over.** You can see the result in the following table.

Run | commit | commit_log_entry | commit_file | file | file_identity | findings | metric_value
-- | -- | -- | -- | -- | -- | -- | -- 
1 | 293 | 3856 | 79550 | 1746 | 983
2 | 293 | 4097 | 92347 | 1864 | 983
3 | 293 | 4086 | 55388 | 1597 | 983
4 | 293 | 4097 | 92347 | 1864 | 983
5 | 293 | 4061 | 74902 | 1680 | 983
6 | 293 | 4097 | 92347 | 1864 | 983 | 26163 | 36035
7 | 293 | 4097 | 56114 | 1609 | 983 | 12810 | 17534

**Explanation**
In run 1 to 5, I only created the project in the database and let the analyzer fill the columns "commit" to "file_identity". This works with no exception, but as you can see there are some huge differences in the amount of tabel entries, especially in table commit_file.
In run 6 and 7, I did the same as before but additionally added two analyzers and an analyzingJob, so that "findings" and "metric_value" are filled. In run 6, no exception occured, so here all tables seem to be completely filled. But in run 7, I had the exception you can see in the 1st post numerous times.

Maybe there is something wrong with the jobs or the timing of those. Especially the table "commit_file" shows some huge differences concerning the number of rows after each run. And this seems to be the table where the relation between commit and file cannot be found during analyzing, which then results in the IllegalStateException.

Hope that helps ;-)

**Comment by thombergs** [comment]
Thanks for the analysis!

I fixed a bug that skipped some commits due to an error in (the usage of?) JGit. All commits are being scanned now.

I ran a few tests similiar to run 1 through 5 of your test and all had the same numbers. However, since I couldn't reproduce the problem in the first place, could you please run your test runs again?

**Comment by pschild** [comment]
Alright. I ran 13 tests, but still some of them failed :-(
Here are the results:

The first 10 tests were successful. I created only the project in the database (no analyzing):

run | commit | commit_log_entry | commit_file | file | file_identity
-- | -- | -- | -- | -- | --
1-10 | 374 | 5.117 | 113.694 | 2.467 | 1.119

Then, I ran some tests with analyzers. Steps were as follows:

1. create project
2. add file pattern
3. add analyzer config
4. add analyzing job
5. add modules

I sent those requests directly in a row to the API.

run | commit | commit_log_entry | commit_file | file | file_identity
-- | -- | -- | -- | -- | --
11 | 374 | 5.117 | 62.979 | 1.768 | 1.111
12 | 374 | 5.117 | 93.042 | 2.307 | 1.119
13 | 374 | 5.117 | 113.694 | 2.467 | 1.119

In run 11 and 12, I didn't let the analyzing jobs run through, because I saw that there were entries missing. In run 13, all tables seemed to be completely filled. While I was waiting for the analyzing being done I observed the console, and although the row counts are the same as in the first 10 runs, I got IllegalStateExceptions...

I searched the log for those exceptions and figured out that all in all there are 10 different files that cannot be found in 15 different commits. See the attached txt file for the list: [exception-analysis.txt](https://github.com/reflectoring/coderadar/files/736877/exception-analysis.txt)
It's noticeable that most of those commits were made by other contributors. One of the commits is a merge commit. Don't know if this could be the reason?!

**Comment by thombergs** [comment]
Thanks. At least the first part is stable now.

I will look further into this tonight.

**Comment by thombergs** [comment]
OK, I can reproduce it now and did some investitating. The source of this evil lies in the (lack of) handling of commits with multiple parents (merges), which ironically is the first issue I created for coderadar: https://github.com/reflectoring/coderadar/issues/1.

I have to do some more thinking on how to handle multiple parents, since all mechanisms currently rely on sequential commits.

**Comment by thombergs** [comment]
The coderadar project is successfully running through, now. I made some changes to handle commit parents in a consistent way, which is only to always only consider the first parent, which should be the one interesting for us. 

Please try again and report if it works :).

**Comment by pschild** [comment]
Hi,

nice, it seems to work now 👌 I tested with Coderadar itself and 2 additional repos, and didn't receive any exception.
I will close this issue.
