### ISSUE TITLE
make Job Trigger interval configurable

### ISSUE THREAD

**Issue by thombergs** [reflectoring/coderadar#120]
Coderadar contains a couple Trigger classes (all ending with ...Trigger, like `AnalyzeCommitJobTrigger`). These classes each have one method annotated with `@Scheduled(fixedDelay = 5000)` which tells Spring to call this method every 5000 milliseconds.

It would be great to have this time interval configurable instead of fixed at 5000 milliseconds.

1. create a configuration parameter like the other configuration parameters (see `MasterConfigurationParameter` for example).
2. tell Springs scheduler to take this new parameter as input instead of the fixed value. See
http://stackoverflow.com/questions/14630539/scheduling-a-job-with-spring-programmatically-with-fixedrate-set-dynamically/14632758#14632758

**Entry points into the code:**
* org.wickedsource.coderadar.job.analyze.AnalyzeCommitJobTrigger
* org.wickedsource.coderadar.job.scan.commit.CommitScannerTrigger
* org.wickedsource.coderadar.job.scan.file.FileScannerTrigger
* org.wickedsource.coderadar.job.merge.LogMergerTrigger

**Comment by rzpio** [comment]
The job framework is dropped (see #204), so this is no longer needed. If a job framework is added again, the issue can be opened again.
