### ISSUE TITLE
Clean working directory when Project is deleted

### ISSUE THREAD

**Issue by thombergs** [reflectoring/coderadar#126]
When a project is deleted via the [REST API](http://www.reflectoring.io/coderadar/1.0.0-SNAPSHOT/docs/restapi.html#_deleting_a_project), the project is currently only deleted from the database.

Additionally, the deleted project's git clone should also be deleted from the working directory. Otherwise, if you create a new project with the same name, the old got clone will be used.

Additional Infos:
* the working directory is configured using the configuration parameter `coderadar.workdir`
* the class `ProjectDeleter` is responsible for deleting a project.

**Comment by maximAtanasov** [comment]
Project deletion functions properly now.
