### ISSUE TITLE
Create a PID file on startup

### ISSUE THREAD

**Issue by thombergs** [reflectoring/coderadar#140]
On startup, create a PID file containing the process id.

Path to PID file must be configurable in application.properties.

**Comment by matthiasbalke** [comment]
You don't have to do this within your java application. Just write the PID file while starting your application from your startup script. Take a look at this gist: https://gist.github.com/matthiasbalke/ab14bcc37a11b848f16a

**Comment by thombergs** [comment]
The gist you mentioned creates a PID for the Shell script process not for the java process. However, creating a PID is no longer necessary, since you can create an executable JAR as explained here: http://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html#deployment-systemd-service

So, this is no longer necessary, closing the issue.
