### ISSUE TITLE
Admin Guide: Starting Coderadar standalone

### ISSUE THREAD

**Issue by thombergs** [reflectoring/coderadar#147]
The Admin Guide (http://reflectoring.github.io/coderadar/current/docs/admin.html) contains a section "Starting coderadar standalone" which should describe exactly what has to be done to start coderadar from the executable WAR file that is part of the distribution.

The Guide contains a reference to this ticket that should then be replaced

**Comment by maximAtanasov** [comment]
Done in #331.
