### ISSUE TITLE
Token Refresh

### ISSUE THREAD

**Issue by thombergs** [reflectoring/coderadar#152]
Support token refresh in the coderadar-app, so that a new token is requested with the refresh token.

See:
* http://www.reflectoring.io/coderadar/current/docs/restapi.html#_login
* http://www.reflectoring.io/coderadar/current/docs/restapi.html#_authentication
* http://www.reflectoring.io/coderadar/current/docs/restapi.html#_token_refresh

**Comment by rzpio** [comment]
@maximAtanasov, Are you implementing this?

**Comment by maximAtanasov** [comment]
Yes, Login, Registration with tokens + token refresh on expiration have been implemented.

**Comment by rzpio** [comment]
Already done? Wow, nice! 👍 
I'm excited about the PR! 😃
