### ISSUE TITLE
User Interface for creating and configuring a project 

### ISSUE THREAD

**Issue by thombergs** [reflectoring/coderadar#153]
Provide a user interface for configuring a project. The REST API provides several endpoints for configuring certain aspects of a project (see list below). 

* http://www.reflectoring.io/coderadar/current/docs/restapi.html#_creating_a_project
* http://www.reflectoring.io/coderadar/current/docs/restapi.html#_updating_a_project
* http://www.reflectoring.io/coderadar/current/docs/restapi.html#_setting_a_project_s_file_patterns
* http://www.reflectoring.io/coderadar/current/docs/restapi.html#_adding_an_analyzer_configuration
* http://www.reflectoring.io/coderadar/current/docs/restapi.html#_creating_a_module

**Comment by rzpio** [comment]
Duplicate, see #215.
