### ISSUE TITLE
non-linear increase of computation time for AssociateGitLogJob with increasing number of commits

### ISSUE THREAD

**Issue by thombergs** [reflectoring/coderadar#156]
When submitting a large project with many commits to coderadar, the AssociateGitLogJob runs longer for each commit until it is unacceptably long.

Analyze the cause of this.

**Comment by thombergs** [comment]
also see comment from pschild on issue #117.

I tested it, too, with junit4 with the result that the file association indeed took longer the more data was in the database. However at the end it took only 3 seconds for each commit, which is acceptable in my opinion, since it should only be done once for each repo.

30 seconds as measured by @pschild is not acceptable, however. That may be caused by different hardware. What database did you use?

The most time-consuming step is inserting the unchanged files for each commit at CommitToFileAssociator#associateWithUnchangedFiles(). We should check http://blog.jhades.org/performance-tuning-of-spring-hibernate-applications/ for some improvements when doing a lot of inserts into the database.

**Comment by pschild** [comment]
I ran the test with junit4 again, but this time I used a different MySQL database: in the first run, I used a MySQL on a webserver (XAMPP and phpMyAdmin) - now I used a MySQL 5.7.15 which I installed on my Windows machine (without a webserver). The performance is much better now, it took only 3 secs/commit at the end for me as well.

**Comment by rzpio** [comment]
This should be fixed with the switch to Neo4j. Evaluate again after the switch.

**Comment by maximAtanasov** [comment]
AssociateGitLogJob is no longer in the project after the refactoring. The size of the project now lineary increases the save/computation time.
