### ISSUE TITLE
Commit History

### ISSUE THREAD

**Issue by thombergs** [reflectoring/coderadar#16]
A list of all commits, visualized as a tree of commit nodes. 

For each commit the following data is displayed:
- commit message
- committer
- commit date
- commit hash
- number of findings of a seleted metric within this commit

User input fields:
- date range picker: show only the commits within the specified date range
- metric dropdown to select the metric to be displayed for each commit
- button to load the next X commits (by default only 20 or so should be displayed)

**Comment by thombergs** [comment]
The git commit tree may be visualized with http://gitgraphjs.com/

**Comment by maximAtanasov** [comment]
Closed in #337.
