### ISSUE TITLE
Evaluate Graph Database for Persistence

### ISSUE THREAD

**Issue by thombergs** [reflectoring/coderadar#167]
Find out if a graph database like neo4j is better suited to store coderadar's data.

In the current relational database, each commit is associated via join table with each file that was part in that commit, which results in a very large amount of join table entries (~ 70 million entries for a month of commits in a project with ~ 1 million LOC and ~ 30 committers). The large number of entries makes querying the metric values very slow, even when using indices.

**Comment by thombergs** [comment]
Querying the commit structure and files that were modified within those commits definitely is more straightforward with a graph database (see screenshot). This way, files that were not modified in a commit do no longer have to be connected via join table with that commit, but instead you can query them via their parent commits. Thus, saving a lot of those join table entries.

![graph_query](https://cloud.githubusercontent.com/assets/1363578/24335132/b3d3061e-1277-11e7-9315-5e9de69c904f.png)

**Comment by rzpio** [comment]
The switch to the graph database Neo4j will be done soon. See also #202 and #204.
