### ISSUE TITLE
Remove HATEOAS

### ISSUE THREAD

**Issue by thombergs** [reflectoring/coderadar#191]
Remove HATEOAS support, since we don't really evaluate it anyways.

**Comment by KilianKrause** [comment]
Do you only want to remove the hypermedia support of HATEOAS, or do you want to remove the whole library from the project? Removing the whole library would mean, that we have no paged-resources-information and no resource-support available anymore.

**Comment by zwiebelbrot** [comment]
Merged, see #207. Further discussions about pagination in #214.
