### ISSUE TITLE
Metric: Create Levelized Structure Map from Source code

### ISSUE THREAD

**Issue by thombergs** [reflectoring/coderadar#201]
As a user, I want to see a "levelized structure map" (like in Structure101) of the codebase at a certain point in time.

A levelized structure map shows packages with dependencies from top to bottom. Circular Dependencies (from bottom to top) are displayed with dotted arrows.

I can expand and contract packages in order to navigate through the codebase.

![lsm](https://user-images.githubusercontent.com/1363578/52853989-75b32c80-311d-11e9-8de8-f111f8e1a2b3.png)

**Comment by jo2** [comment]
under which conditions should dependencies be placed next to each other and under which conditions should a dependenciy be placed below an other?

**Comment by maximAtanasov** [comment]
Closed in #324
