### ISSUE TITLE
Re-Structure Architecture

### ISSUE THREAD

**Issue by thombergs** [reflectoring/coderadar#202]
Review the architecture and define a new target architecture.

**Comment by thombergs** [comment]
First draft of a new target architecture:

![coderadar-arc](https://user-images.githubusercontent.com/1363578/53744147-ad9bcd00-3e9c-11e9-85fc-d71b603d3529.png)

Within the core, we have three modules:
* **projectadministration** is responsible for setting up and configuring projects 
* **analyzer** is responsible for fetching the remote git repo and analyzing the files
* **metricquery** is responsible for database queries concerning all things that have to with metrics (this is a read-only module)

The core provides incoming and outgoing ports to the surrounding adapter:
* the **coderadar-rest-api** adapter provides a rest-api for all operations of the core that should be exposed
* the **coderadar-graph** (or GFC?) adapter provides access to the Graph Database

**Proposed package structure for the core:**
![package-structure](https://user-images.githubusercontent.com/1363578/53744445-5d713a80-3e9d-11e9-879f-36f7fd89e5d2.png)

* CreateProjectService implements CreateProjectUseCase
* CreateProjectUseCase provides a method `createProject(CreateProjectCommand command)`
* for starters, we simply put Jackson and perhaps even Neo4J annotations to the domain classes and add mapping later as necessary

**Comment by rzpio** [comment]
I think coderadar-graph for the graph database adapter is the better name. :wink: It then remains at least uniform.

**Comment by thombergs** [comment]
TODO: go through the code and re-structure into target architecture (with JPA, Hibernate and Spring Data, for now).

**Comment by maximAtanasov** [comment]
The architecture shift has been completed.
