### ISSUE TITLE
Add functionality to change/remove file patterns

### ISSUE THREAD

**Issue by KilianKrause** [reflectoring/coderadar#210]

**Comment by maximAtanasov** [comment]
Doesn't this work already? It seems to work for me. I can set and remove include/excluded file patterns.

**Comment by maximAtanasov** [comment]
Doesn't this work already? It seems to work for me. I can set and remove included/excluded file patterns.

**Comment by zwiebelbrot** [comment]
Yes, the file patterns can be added, changed and deleted via the REST endpoint `/projects/x/files`. But why do I change a list of file patterns via one endpoint and for example for the analyzer configurations I have three endpoints: One to add, one to change and one to delete an analyzer. The REST API in _3.3.4. Setting a Project’s File Patterns_ also doesn't directly indicate that file patterns can be changed and deleted via the endpoint.

Either we should deal with file patterns in the same way as analyzer configurations (and thus offer three endpoints) or we should clarify the current case in the REST API.

**Comment by maximAtanasov** [comment]
No longer an issue in master (after new-architecture merge). Separate endpoints for manipulating file patterns now exist. See #292
