### ISSUE TITLE
Wrong values from LoC analyzer

### ISSUE THREAD

**Issue by trzpiot** [reflectoring/coderadar#220]
The LoC analyzer returns incorrect values. Tested on the following queries for [this](https://github.com/adessoAG/budgeteer) project:
```
127.0.0.1:8080/projects/1/metricvalues/tree (Querying metrics for all files in a single commit)
127.0.0.1:8080/projects/1/metricvalues/perCommit (Querying metric values of a commit)
```

The Commit [d076f60c702c87408933e8fb2ca388f80dc956ff](https://github.com/adessoAG/budgeteer/tree/d076f60c702c87408933e8fb2ca388f80dc956ff) was used for the queries.

The following file displays 1369 sloc and 16 cloc. Correct would be 176 sloc and 2 cloc (see the file in the commit [here](https://github.com/adessoAG/budgeteer/blob/d076f60c702c87408933e8fb2ca388f80dc956ff/budgeteer-aproda-importer/src/main/java/org/wickedsource/budgeteer/importer/aproda/AprodaWorkRecordsImporter.java)). The picture shows the wrong values of the query _Querying metrics for all files in a single commit_. The summed values of all files from the query _Querying metric values of a commit_ are also wrong.

![wrongvalues](https://user-images.githubusercontent.com/33252305/53693723-af826500-3da4-11e9-84df-d32f05972096.PNG)

The values of other files are also wrong (for example this file [here](https://github.com/adessoAG/budgeteer/blob/d076f60c702c87408933e8fb2ca388f80dc956ff/budgeteer-report-exporter/src/main/java/org/wickedsource/budgeteer/SheetTemplate/TemplateWriter.java), the query returns 659 sloc and 10 cloc).
My guess is that the analyzer reads the files from the database multiple times and sums the values. For some files the values are correct, for example this file [here](https://github.com/adessoAG/budgeteer/blob/d076f60c702c87408933e8fb2ca388f80dc956ff/budgeteer-report-exporter/src/main/java/org/wickedsource/budgeteer/SheetTemplate/SheetTemplateSerializable.java).

**Comment by maximAtanasov** [comment]
This should have been fixed after the refactoring. Please open new issues for inconsistencies.
