### ISSUE TITLE
Missing local.application.properties

### ISSUE THREAD

**Issue by maximAtanasov** [reflectoring/coderadar#222]
The file `coderadar-server/coderadar-core/local.application.properties` is missing in the master branch.

**Comment by rzpio** [comment]
The file was removed in #209. The user should adapt the template _local.application.properties.template_ and rename it to _local.application.properties_. The configurations should not be versioned.

**Comment by maximAtanasov** [comment]
In that case, could we add the line `coderadar.cors.enabled=true` to the template? This way I don't have to write it myself each time I clone master.

**Comment by rzpio** [comment]
Of course, I forgot. Added in #223.

**Comment by maximAtanasov** [comment]
That was fast :). Thanks
