### ISSUE TITLE
Issue with analyzing jobs

### ISSUE THREAD

**Issue by maximAtanasov** [reflectoring/coderadar#225]
`GET 127.0.0.1:8080/projects/{id}/analyzingJob` always returns `{ fromDate: 0, active: true } `
even when the job has been completed.

**Comment by rzpio** [comment]
It's not a direct bug, it's wanted. The question is whether this is a good solution. The job framework will be thrown overboard anyway.

The AnalyzingJob is executed permanently. If new commits are scanned, they are also analyzed by the AnalyzingJob. Therefore the job is always active. It would make sense to terminate the job when the analysis has been completed. If new commits are scanned, a new AnalyzingJob should be started.

**Comment by maximAtanasov** [comment]
The new endpoint is `/analyzingStatus` and it returns true or false.
