### ISSUE TITLE
Which VCSs do we want to support?

### ISSUE THREAD

**Issue by trzpiot** [reflectoring/coderadar#227]
[Do we really need to support other VCSs](https://trends.google.com/trends/explore?date=today%205-y&q=git,svn,mercurial)? In the README.md we are talking about "runs code analyzers on your version control system". Currently only Git repositories are supported. This will probably not change in the near future, so it might make sense to concentrate on Git first.

**Comment by KilianKrause** [comment]
I also think we should focus on git repositories.

**Comment by trzpiot** [comment]
The focus is set on Git. Other VCS can be integrated as adapters afterwards.
