### ISSUE TITLE
Develop a Neo4j adapter

### ISSUE THREAD

**Issue by trzpiot** [reflectoring/coderadar#253]
The Neo4j adapter shall implement the driven ports of the core. This should make it possible to store data in the graph database Neo4j via the adapter. In addition, the core should be completely independent of the implementation due to the adapter design pattern, which makes it much easier to switch to another database. In addition, the representation of the data as graphs allows a better representation of the Git graph.
Within the core, the domain is defined that is initially used by the Neo4j adapter. After the implementation the use of a mapper can be discussed.
The graph should be based on the one from #204 (see image).

![](https://user-images.githubusercontent.com/33252305/53802919-6b799680-3f43-11e9-9f27-3235f0c256a4.png)

**Comment by maximAtanasov** [comment]
@trzpiot 
I'm posting the new graph you've made here
![graph](https://user-images.githubusercontent.com/32562426/59412140-13152900-8dbd-11e9-9d5c-0f84df5e9f07.png)
