### ISSUE TITLE
To Page Bottom for long views

### ISSUE THREAD

**Issue by jo2** [reflectoring/coderadar#273]
For example in the commit view scolling to the bottom when showing 50 or 100 commits is a pain. A button "scroll to bottom" would be nice. It works with a shortcut `strg+arrow_down` but it would be nicer using a button.

**Comment by jo2** [comment]
Alternatively, the paging options could be shown at the top and the bottom of the page. I think that should fix it, too, because wanting to use the pagination options is the main reeason for scrolling directly to the bottom.

**Comment by maximAtanasov** [comment]
Fixed in #292 , paging options are now also available at the top of the list.
