### ISSUE TITLE
Problem with creating modules

### ISSUE THREAD

**Issue by jo2** [reflectoring/coderadar#284]
Creating a module doesn't allways work:
Request Body: 
```
{
  "path" : "budgeteer-resourceplan-importer"
}
```

Response: 
```
{
  "id": 4200
}
```

Executing the request multiple times returns a new id each.
Listing the projects modules returns:
```
[
  {
    "id": 1662,
    "path": "budgeteer-web-interface/"
  },
  {
    "id": 51,
    "path": "budgeteer-importer-api/"
  }
]
```
Deleting modules which are not shown returns 200 (OK), which is the same as deleting existing modules.
Deleting the project also won't delete these modules.
These Modules do appear in the database but are not returned in the query.

**Comment by maximAtanasov** [comment]
Fixed in #292
