### ISSUE TITLE
getProjectPort.get(projectId) should not throw ProjectNotFoundException

### ISSUE THREAD

**Issue by thombergs** [reflectoring/coderadar#285]
`getProjectPort.get(projectId)` in `GetMetricValuesOfCommitService` for example is called without using the return value just to trigger an exception if the project does not exist. This is a smell.

Instead of throwing a `ProjectNotFoundException`, build another method `projectExists` that returns true or false. Depending on the result, throw the exception in the use case and not in the adapter.

**Comment by KilianKrause** [comment]
This will be fixed in the architecture refactoring.
