### ISSUE TITLE
Dependency-Map integration

### ISSUE THREAD

**Issue by jo2** [reflectoring/coderadar#296]
To integrate the Dependency-Map module we need some more ports:
* delete a cloned Repository (for testing I need to clone a Repository, after the tests I want to remove it so the tests are repeatable without running into "project name already in use")
* do a TreeWalk through a filetree of a given Commit and Repository, for each pathString in treewalk a method should be called. That can be realised with lambdas (https://stackoverflow.com/a/2186993/5922344)
* get a list with all DiffEntries between to commits

**Comment by maximAtanasov** [comment]
Closed in #324
