### ISSUE TITLE
Find a way to visualize findings

### ISSUE THREAD

**Issue by KilianKrause** [reflectoring/coderadar#333]
We need to tell the user where specific metrics appear. We probably need to save the file content in the db or use jgit to get the file content.

**Comment by maximAtanasov** [comment]
Findings can be seen in the file browser as of PR #345 .

**Comment by KilianKrause** [comment]
So this issue can be closed?

**Comment by maximAtanasov** [comment]
I'm not sure. There is still a lot of things we can do with findings. But maybe we can open new issues for other features and close this one.
