### ISSUE TITLE
Throttle continuously failing jobs

### ISSUE THREAD

**Issue by thombergs** [reflectoring/coderadar#53]
Currently, the job triggers run every couple seconds to evaluate if a new job is to be placed into the queue. If a job fails within the couple seconds it will be queued again and again, each time failing. The job then blocks a job executing server node.

Jobs that continuously fail (say 3 times in a row) should be given a timeout of 10 minutes or so until it is queued again. The trigger logic should be extended by this rule.

**Comment by rzpio** [comment]
The job framework is dropped (see #204), so this is no longer needed. If a job framework is added again, the issue can be opened again.
