### ISSUE TITLE
Cut dependencies between ResourceAssemblers and RestControllers

### ISSUE THREAD

**Issue by thombergs** [reflectoring/coderadar#54]
Currently, the ResourceAssemblers access the Controllers they link to to create URIs for Hypermedia links. This leads to circular dependencies between all rest api packages.

The URIs should be all put in a simple URIRegistry or so to cut these circular dependencies.

**Comment by maximAtanasov** [comment]
ResourceAssemblers no longer exist after mergin #292 and the rest package is now it's own gradle module with a dependency on the core.
