### ISSUE TITLE
Automatic failover for master server nodes.

### ISSUE THREAD

**Issue by thombergs** [reflectoring/coderadar#57]
If the property coderadar.master is set, the job triggers are activated on that node, meaning that it triggers jobs that are then processed by the slave server nodes.

If the master node shuts down, no jobs will be triggered anymore, meaning no analyses take place anymore.

Devise a communication mechanism that automatically lets another server node take over the master role.

**Comment by thombergs** [comment]
Should be added at a later date, since high availability is not a concern for now. The worst that will happen if the master node dies is that no new incoming commits are being scanned and analyzed. A restart of the Master node will fix this. 

Scalability is more important than high availability for now.

**Comment by rzpio** [comment]
The job framework is dropped (see #204), so this is no longer needed. If a job framework is added again, the issue can be opened again.
